import { Airport } from '../types';

export const airports: Airport[] = [
  { iata: 'ATL', name: 'Hartsfield-Jackson Atlanta International Airport', city: 'Atlanta', country: 'US' },
  { iata: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles', country: 'US' },
  { iata: 'ORD', name: "O'Hare International Airport", city: 'Chicago', country: 'US' },
  { iata: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas', country: 'US' },
  { iata: 'DEN', name: 'Denver International Airport', city: 'Denver', country: 'US' },
  { iata: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York', country: 'US' },
  { iata: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco', country: 'US' },
  { iata: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle', country: 'US' },
  { iata: 'LAS', name: 'Harry Reid International Airport', city: 'Las Vegas', country: 'US' },
  { iata: 'MCO', name: 'Orlando International Airport', city: 'Orlando', country: 'US' },
  { iata: 'EWR', name: 'Newark Liberty International Airport', city: 'Newark', country: 'US' },
  { iata: 'MIA', name: 'Miami International Airport', city: 'Miami', country: 'US' },
  { iata: 'CLT', name: 'Charlotte Douglas International Airport', city: 'Charlotte', country: 'US' },
  { iata: 'PHX', name: 'Phoenix Sky Harbor International Airport', city: 'Phoenix', country: 'US' },
  { iata: 'IAH', name: 'George Bush Intercontinental Airport', city: 'Houston', country: 'US' },
  { iata: 'BOS', name: 'Boston Logan International Airport', city: 'Boston', country: 'US' },
  { iata: 'MSP', name: 'Minneapolis-Saint Paul International Airport', city: 'Minneapolis', country: 'US' },
  { iata: 'FLL', name: 'Fort Lauderdale-Hollywood International Airport', city: 'Fort Lauderdale', country: 'US' },
  { iata: 'DTW', name: 'Detroit Metropolitan Wayne County Airport', city: 'Detroit', country: 'US' },
  { iata: 'PHL', name: 'Philadelphia International Airport', city: 'Philadelphia', country: 'US' },
  { iata: 'LGA', name: 'LaGuardia Airport', city: 'New York', country: 'US' },
  { iata: 'BWI', name: 'Baltimore/Washington International Airport', city: 'Baltimore', country: 'US' },
  { iata: 'SLC', name: 'Salt Lake City International Airport', city: 'Salt Lake City', country: 'US' },
  { iata: 'SAN', name: 'San Diego International Airport', city: 'San Diego', country: 'US' },
  { iata: 'DCA', name: 'Ronald Reagan Washington National Airport', city: 'Washington', country: 'US' },
  { iata: 'IAD', name: 'Washington Dulles International Airport', city: 'Washington', country: 'US' },
  { iata: 'TPA', name: 'Tampa International Airport', city: 'Tampa', country: 'US' },
  { iata: 'HNL', name: 'Daniel K. Inouye International Airport', city: 'Honolulu', country: 'US' },
  { iata: 'PDX', name: 'Portland International Airport', city: 'Portland', country: 'US' },
  { iata: 'STL', name: 'St. Louis Lambert International Airport', city: 'St. Louis', country: 'US' },
  { iata: 'BNA', name: 'Nashville International Airport', city: 'Nashville', country: 'US' },
  { iata: 'AUS', name: 'Austin-Bergstrom International Airport', city: 'Austin', country: 'US' },
  { iata: 'MCI', name: 'Kansas City International Airport', city: 'Kansas City', country: 'US' },
  { iata: 'RDU', name: 'Raleigh-Durham International Airport', city: 'Raleigh', country: 'US' },
  { iata: 'SMF', name: 'Sacramento International Airport', city: 'Sacramento', country: 'US' },
  { iata: 'SNA', name: 'John Wayne Airport', city: 'Santa Ana', country: 'US' },
  { iata: 'SJC', name: 'San Jose International Airport', city: 'San Jose', country: 'US' },
  { iata: 'OAK', name: 'Oakland International Airport', city: 'Oakland', country: 'US' },
  { iata: 'CLE', name: 'Cleveland Hopkins International Airport', city: 'Cleveland', country: 'US' },
  { iata: 'PIT', name: 'Pittsburgh International Airport', city: 'Pittsburgh', country: 'US' },
  { iata: 'CMH', name: 'John Glenn Columbus International Airport', city: 'Columbus', country: 'US' },
  { iata: 'IND', name: 'Indianapolis International Airport', city: 'Indianapolis', country: 'US' },
  { iata: 'MKE', name: 'Milwaukee Mitchell International Airport', city: 'Milwaukee', country: 'US' },
  { iata: 'CVG', name: 'Cincinnati/Northern Kentucky International Airport', city: 'Cincinnati', country: 'US' },
  { iata: 'SAT', name: 'San Antonio International Airport', city: 'San Antonio', country: 'US' },
  { iata: 'MSY', name: 'Louis Armstrong New Orleans International Airport', city: 'New Orleans', country: 'US' },
  { iata: 'JAX', name: 'Jacksonville International Airport', city: 'Jacksonville', country: 'US' },
  { iata: 'ABQ', name: 'Albuquerque International Sunport', city: 'Albuquerque', country: 'US' },
  { iata: 'OMA', name: 'Eppley Airfield', city: 'Omaha', country: 'US' },
  { iata: 'BDL', name: 'Bradley International Airport', city: 'Hartford', country: 'US' },
  { iata: 'RSW', name: 'Southwest Florida International Airport', city: 'Fort Myers', country: 'US' },
  { iata: 'PBI', name: 'Palm Beach International Airport', city: 'West Palm Beach', country: 'US' },
  { iata: 'BUF', name: 'Buffalo Niagara International Airport', city: 'Buffalo', country: 'US' },
  { iata: 'RIC', name: 'Richmond International Airport', city: 'Richmond', country: 'US' },
  { iata: 'ORF', name: 'Norfolk International Airport', city: 'Norfolk', country: 'US' },
  { iata: 'TUS', name: 'Tucson International Airport', city: 'Tucson', country: 'US' },
  { iata: 'OKC', name: 'Will Rogers World Airport', city: 'Oklahoma City', country: 'US' },
  { iata: 'MEM', name: 'Memphis International Airport', city: 'Memphis', country: 'US' },
  { iata: 'SDF', name: 'Louisville Muhammad Ali International Airport', city: 'Louisville', country: 'US' },
  { iata: 'MDW', name: 'Chicago Midway International Airport', city: 'Chicago', country: 'US' },
  { iata: 'HOU', name: 'William P. Hobby Airport', city: 'Houston', country: 'US' },
  { iata: 'DAL', name: 'Dallas Love Field', city: 'Dallas', country: 'US' },
  { iata: 'BUR', name: 'Hollywood Burbank Airport', city: 'Burbank', country: 'US' },
  { iata: 'ONT', name: 'Ontario International Airport', city: 'Ontario', country: 'US' },
  { iata: 'LGB', name: 'Long Beach Airport', city: 'Long Beach', country: 'US' },
  { iata: 'ANC', name: 'Ted Stevens Anchorage International Airport', city: 'Anchorage', country: 'US' },
  { iata: 'OGG', name: 'Kahului Airport', city: 'Kahului', country: 'US' },
  { iata: 'LIH', name: 'Lihue Airport', city: 'Lihue', country: 'US' },
  { iata: 'KOA', name: 'Ellison Onizuka Kona International Airport', city: 'Kailua-Kona', country: 'US' },
  { iata: 'RNO', name: 'Reno-Tahoe International Airport', city: 'Reno', country: 'US' },
  { iata: 'BOI', name: 'Boise Airport', city: 'Boise', country: 'US' },
  { iata: 'GEG', name: 'Spokane International Airport', city: 'Spokane', country: 'US' },
  { iata: 'ICT', name: 'Wichita Dwight D. Eisenhower National Airport', city: 'Wichita', country: 'US' },
  { iata: 'DSM', name: 'Des Moines International Airport', city: 'Des Moines', country: 'US' },
  { iata: 'LIT', name: 'Bill and Hillary Clinton National Airport', city: 'Little Rock', country: 'US' },
  { iata: 'TUL', name: 'Tulsa International Airport', city: 'Tulsa', country: 'US' },
  { iata: 'ELP', name: 'El Paso International Airport', city: 'El Paso', country: 'US' },
  { iata: 'COS', name: 'Colorado Springs Airport', city: 'Colorado Springs', country: 'US' },
  { iata: 'SYR', name: 'Syracuse Hancock International Airport', city: 'Syracuse', country: 'US' },
  { iata: 'ROC', name: 'Frederick Douglass Greater Rochester International Airport', city: 'Rochester', country: 'US' },
  { iata: 'ALB', name: 'Albany International Airport', city: 'Albany', country: 'US' },
  { iata: 'PVD', name: 'T.F. Green International Airport', city: 'Providence', country: 'US' },
  { iata: 'PWM', name: 'Portland International Jetport', city: 'Portland', country: 'US' },
  { iata: 'BTV', name: 'Burlington International Airport', city: 'Burlington', country: 'US' },
  { iata: 'GSP', name: 'Greenville-Spartanburg International Airport', city: 'Greenville', country: 'US' },
  { iata: 'CHS', name: 'Charleston International Airport', city: 'Charleston', country: 'US' },
  { iata: 'SAV', name: 'Savannah/Hilton Head International Airport', city: 'Savannah', country: 'US' },
  { iata: 'XNA', name: 'Northwest Arkansas National Airport', city: 'Fayetteville', country: 'US' },
  { iata: 'FAT', name: 'Fresno Yosemite International Airport', city: 'Fresno', country: 'US' },
  { iata: 'GRR', name: 'Gerald R. Ford International Airport', city: 'Grand Rapids', country: 'US' },
  { iata: 'HSV', name: 'Huntsville International Airport', city: 'Huntsville', country: 'US' },
  { iata: 'LEX', name: 'Blue Grass Airport', city: 'Lexington', country: 'US' },
  { iata: 'MAF', name: 'Midland International Air and Space Port', city: 'Midland', country: 'US' },
  { iata: 'MSN', name: 'Dane County Regional Airport', city: 'Madison', country: 'US' },
  { iata: 'PNS', name: 'Pensacola International Airport', city: 'Pensacola', country: 'US' },
  { iata: 'SRQ', name: 'Sarasota-Bradenton International Airport', city: 'Sarasota', country: 'US' },
  { iata: 'SHV', name: 'Shreveport Regional Airport', city: 'Shreveport', country: 'US' },
  { iata: 'DAY', name: 'Dayton International Airport', city: 'Dayton', country: 'US' },
  { iata: 'BHM', name: 'Birmingham-Shuttlesworth International Airport', city: 'Birmingham', country: 'US' },
  { iata: 'VPS', name: 'Destin-Fort Walton Beach Airport', city: 'Destin', country: 'US' },
];

export function searchAirports(query: string): Airport[] {
  const q = query.toLowerCase().trim();

  if (q.length < 1) {
    return [];
  }

  const results = airports.filter((airport) => {
    return (
      airport.iata.toLowerCase().includes(q) ||
      airport.city.toLowerCase().includes(q) ||
      airport.name.toLowerCase().includes(q)
    );
  });

  return results.slice(0, 10);
}
